name: flutter_template
description: Bitforge Flutter Template
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  app_settings: ^5.1.1
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5
  flutter_riverpod: ^2.4.5
  gap: ^3.0.1
  go_router: ^12.1.0
  google_fonts: ^6.1.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.1

dev_dependencies:
  custom_lint: ^0.5.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/translations/
